import { ThemeProvider } from "@/components/layouts/theme-provider";
import { AuthProvider } from "@/context/authContext";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Provider from "./_provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Mytharc",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          GeistSans.variable,
        )}
      >
        <Provider>
          <AuthProvider>
            <ThemeProvider>
              <Toaster />
              {children}{" "}
            </ThemeProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
